export const GLOSSARY = {
  leads: "Total de contactos (leads) creados en HubSpot dentro de la ventana seleccionada. Fórmula: conteo de contactos con createdate en el período.",
  qualified: "Leads marcados como calificados (MQL/SQL u oportunidad). Fórmula: conteo de contactos cuyo lifecycle stage es marketingqualifiedlead, salesqualifiedlead u opportunity.",
  meetings: "Citas o reuniones agendadas. Fórmula: conteo de contactos con una reunión registrada (meeting/cita) en el período.",
  reservations: "Reservas confirmadas (clientes ganados). Fórmula: conteo de contactos convertidos en cliente / reserva en el período.",
  adSpend: "Inversión total en pauta (Meta Ads) en el período. Fórmula: Σ spend de todas las campañas activas.",
  revenue: "Ingreso atribuido a las reservas del período. Fórmula: Σ monto de contrato de las reservas confirmadas.",
  showUpRate: "Tasa de asistencia efectiva: de las citas agendadas, cuántas avanzaron a reserva. Fórmula: reservas ÷ citas.",
  forecastReservations: "Proyección de reservas para el próximo período, derivada de la tendencia histórica de la serie. Fórmula: proyección sobre reservas observadas (media móvil / tendencia).",
  cpl: "Costo por lead. Fórmula: inversión en pauta ÷ leads.",
  cpql: "Costo por lead calificado. Fórmula: inversión en pauta ÷ leads calificados.",
  costPerReservation: "Costo por reserva (CPR). Fórmula: inversión en pauta ÷ reservas.",
  cac: "Costo de adquisición de cliente. Fórmula: inversión en pauta ÷ clientes (o reservas si no hay clientes).",
  roas: "Retorno sobre la inversión publicitaria. Fórmula: ingreso atribuido ÷ inversión en pauta.",
  meetingToReservation: "Conversión de cita a reserva. Fórmula: reservas ÷ citas.",
  qualifiedToMeeting: "Conversión de lead calificado a cita agendada. Fórmula: citas ÷ leads calificados. Mide qué tan bien el equipo convierte calificados en reuniones.",
  funnel: "Embudo comercial por etapa. Muestra el volumen y la caída entre Leads → Calificados → Citas → Reservas. Cada barra = conteo de contactos en esa etapa.",
  spendVsReservations: "Diagnóstico de eficiencia por campaña: barras apiladas = embudo (calificados → citas → reservas), línea = inversión (spend) en eje derecho. Identifica campañas que gastan sin convertir.",
  cacScatter: "Dispersión de eficiencia por campaña. Eje X = costo por lead calificado (CPQL), eje Y = costo por reserva (CPR). Abajo-izquierda = más eficiente.",
  recommendations: "Recomendación prescriptiva por campaña (escalar/pausar/ajustar) según su costo por reserva vs. el umbral objetivo y si hay reservas atribuidas.",
  kris: "Indicadores de riesgo (KRIs) en vivo. Cada uno compara un valor contra un umbral y se colorea verde/ámbar/rojo según severidad.",
  campaignTable: "KPIs por campaña de Meta Ads. Clic en el nombre para abrir la campaña en Meta Ads Manager. Spend, CPQL, CPR, CTR, frecuencia y ROAS por campaña; exportable a CSV.",
  whatIf: "Simulador what-if: estima el cambio en reservas al reasignar presupuesto, asumiendo el costo por reserva actual constante. Fórmula: reservas ≈ spend simulado ÷ CPR base.",
  repLeaderboard: "Ranking de reservas por asesor (rep). Fórmula: Σ reservas atribuidas a cada owner de HubSpot en el período.",
  repShowUp: "Citas vs. show-up por asesor. Barras = citas; línea = tasa de asistencia (reservas ÷ citas) por rep.",
  repScatter: "Dispersión de desempeño por asesor. X = citas, Y = reservas, tamaño = score promedio del lead. Arriba-derecha = mayor conversión.",
  repTable: "Detalle por asesor: citas, reservas, show-up (reservas÷citas) y score promedio. El nombre se resuelve desde el directorio de owners de HubSpot.",
  leadTemperature: "Distribución del pipeline por temperatura (caliente/tibio/frío) y momentum neto. La temperatura se calcula con un score basado en recencia de actividad, etapa de lifecycle y engagement. Momentum neto = (leads que se calientan) − (leads que se enfrían).",
  prescriptions: "Acciones recomendadas generadas a partir de la clasificación de leads y campañas (acelerar, re-enganchar, reciclar, escalar/pausar/ajustar). Clic en una tarjeta para ver los leads impactados.",
  transitionMatrix: "Matriz de transiciones de temperatura entre el período previo y el actual. Cada celda = nº de leads que pasaron de una temperatura (fila) a otra (columna).",
  topRisk: "Leads con mayor revenue en riesgo: contactos previamente calificados que se están enfriando. Revenue en riesgo = valor potencial del lead × probabilidad de pérdida estimada.",
  forecastReservationsKpi: "Reservas proyectadas para el próximo período según la tendencia de la serie. Fórmula: proyección sobre las reservas observadas (media móvil / tendencia).",
  anomaliesKpi: "Número de puntos atípicos detectados en la serie de reservas (incluye los detectados localmente con z-score sensible). Verde = sin anomalías; ámbar = hay al menos una.",
  reservasForecast: "Reservas reales vs proyección. Línea sólida = reservas observadas; línea punteada = forecast del modelo; banda sombreada = intervalo de confianza. El método se indica en el subtítulo.",
  cprForecast: "Costo por reserva proyectado a partir de snapshots horarios de spend y reservas. Línea sólida = real; punteada = forecast; banda = intervalo de confianza (en USD).",
  anomaliesChart: "Serie de reservas con marcadores de anomalía y una línea de tendencia (media móvil de 3 puntos). Marcador ámbar = anomalía media (|z| ≥ 1.5); rojo = alta (|z| ≥ 2.5). El z-score mide a cuántas desviaciones estándar está el punto de la media de la serie.",
  funnelRadar: "Radar de eficiencia: cada eje es un KPI normalizado como % de su meta (anillo gris = 100%). Combina conversiones del embudo (lead→calificado→cita→reserva→cliente) con señales financieras (ROAS, LTV:CAC). Las hendiduras señalan el cuello de botella.",
  ltvCac: "Relación entre el valor de vida del cliente (LTV) y el costo de adquisición (CAC). Fórmula: LTV ÷ CAC. Saludable ≥ 3x.",
  mer: "Marketing Efficiency Ratio: ingreso total ÷ inversión total en marketing. Mide la eficiencia agregada del gasto.",
  financialContext: "Indicadores económicos que contextualizan el forecast: CAC (costo de adquisición), LTV:CAC (retorno por cliente) y MER (eficiencia agregada del marketing).",
  rootCauses: "Síntesis determinística de causas raíz sobre los datos live: KRIs fuera de umbral, caídas período-vs-período (reservas/ROAS), campañas en fatiga de frecuencia, gasto sin conversión y el cuello de botella del embudo. Cada tarjeta incluye la evidencia numérica que la respalda y una recomendación accionable.",
} as const;

export type GlossaryKey = keyof typeof GLOSSARY;

